aggregator_url = "http://172.17.0.2:8082"

[logging]
filter = "info,xain_fl=debug"
telemetry = { jaeger_endpoint = "jaeger:6831", service_name = "coordinator" }

[api]
bind_address = "0.0.0.0:8081"

[rpc]
bind_address = "0.0.0.0:5555"
aggregator_address = "172.17.0.2:6666"

[federated_learning]
rounds = 10
participants_ratio = 1
min_clients = 2
heartbeat_timeout = 15

[metric_store]
database_url = "http://influxdb:8086"
database_name = "metrics"
